---
- hosts: all
  become: true 
  tasks:
    - name: Install the latest version of Apache2
      ansible.builtin.apt:
        name: apache2
        state: latest
    - name: Start service Apache2, if not started
      ansible.builtin.service:
        name: apache2
        state: started          
        
      
